import { Car } from 'src/app/car/car.model';

export const cars: Car[] = [
  {
    id: '1',
    imageUrl: 'ToyotaCorolla.jpg',
    model: 'Toyota Corolla',
    make: 'Toyota',
    condition: 'Good',
    rating: 4,
    hourlyPrice: 5.99,
  },
  {
    id: '2',
    imageUrl: 'HondaAccord.jpg',
    model: 'Honda Accord',
    make: 'Honda',
    condition: 'Excellent',
    rating: 5,
    hourlyPrice: 6.99,
  },
  {
    id: '3',
    imageUrl: 'FordFusion.jpg',
    model: 'Ford Fusion',
    make: 'Ford',
    condition: 'Good',
    rating: 4,
    hourlyPrice: 7.99,
  },
  {
    id: '4',
    imageUrl: 'NissanMaxima.jpg',
    model: 'Nissan Maxima',
    make: 'Nissan',
    condition: 'Excellent',
    rating: 5,
    hourlyPrice: 7.99,
  },
  {
    id: '5',
    imageUrl: 'ChevroletImpala.jpg',
    model: 'Chevrolet Impala',
    make: 'Chevrolet',
    condition: 'Good',
    rating: 4,
    hourlyPrice: 19.99,
  },
  {
    id: '6',
    imageUrl: 'KiaForte.jpg',
    model: 'Kia Forte',
    make: 'Kia',
    condition: 'Excellent',
    rating: 5,
    hourlyPrice: 6.99,
  },
  {
    id: '7',
    imageUrl: 'HyundaiElantra.jpg',
    model: 'Hyundai Elantra',
    make: 'Hyundai',
    condition: 'Good',
    rating: 4,
    hourlyPrice: 7.99,
  },
  {
    id: '8',
    imageUrl: 'SubaruLegacy.jpg',
    model: 'Subaru Legacy',
    make: 'Subaru',
    condition: 'Excellent',
    rating: 5,
    hourlyPrice: 6.99,
  },
  {
    id: '9',
    imageUrl: 'Mazda6.jpg',
    model: 'Mazda6',
    make: 'Mazda',
    condition: 'Good',
    rating: 4,
    hourlyPrice: 8.99,
  },
  {
    id: '10',
    imageUrl: 'VolkswagenJetta.jpg',
    model: 'Volkswagen Jetta',
    make: 'Volkswagen',
    condition: 'Excellent',
    rating: 5,
    hourlyPrice: 5.99,
  },
];
