import { Car } from 'src/app/car/car.model';

export const cars: Car[] = [
  {
    id: '1',
    imageUrl: 'TeslaModel3.jpg',
    model: 'Tesla Model 3',
    make: 'Tesla',
    condition: 'Good',
    rating: 4.8,
    hourlyPrice: 9.99,
  },
  {
    id: '2',
    imageUrl: 'NissanLeaf.jpg',
    model: 'Nissan Leaf',
    make: 'Nissan',
    condition: 'Excellent',
    rating: 4.5,
    hourlyPrice: 7.49,
  },
  {
    id: '3',
    imageUrl: 'ChevroletBolt.jpg',
    model: 'Chevrolet Bolt',
    make: 'Chevrolet',
    condition: 'Good',
    rating: 4.4,
    hourlyPrice: 6.99,
  },
  {
    id: '4',
    imageUrl: 'BMWi3.jpg',
    model: 'BMW i3',
    make: 'BMW',
    condition: 'Excellent',
    rating: 4.7,
    hourlyPrice: 8.99,
  },
  {
    id: '5',
    imageUrl: 'HyundaiKona.jpg',
    model: 'Hyundai Kona Electric',
    make: 'Hyundai',
    condition: 'Good',
    rating: 4.6,
    hourlyPrice: 7.79,
  },

  {
    id: '6',
    imageUrl: 'FordMustangMachE.jpg',
    model: 'Ford Mustang Mach-E',
    make: 'Ford',
    condition: 'Excellent',
    rating: 4.8,
    hourlyPrice: 9.49,
  },
  {
    id: '7',
    imageUrl: 'VolkswagenID3.jpg',
    model: 'Volkswagen ID.3',
    make: 'Volkswagen',
    condition: 'Good',
    rating: 4.5,
    hourlyPrice: 7.29,
  },

  {
    id: '8',
    imageUrl: 'AudiETron.jpg',
    model: 'Audi e-tron',
    make: 'Audi',
    condition: 'Good',
    rating: 4.4,
    hourlyPrice: 8.19,
  },
  {
    id: '9',
    imageUrl: 'KiaSoulEV.jpg',
    model: 'Kia Soul EV',
    make: 'Kia',
    condition: 'Excellent',
    rating: 4.7,
    hourlyPrice: 6.99,
  },
  {
    id: '10',
    imageUrl: 'JaguarIPACE.jpg',
    model: 'Jaguar I-PACE',
    make: 'Jaguar',
    condition: 'Good',
    rating: 4.6,
    hourlyPrice: 9.99,
  },
];
